SET search_path = "09b3d290", pg_catalog;


CREATE TABLE FILE_REFERENCE
  (
    ID              BIGINT NOT NULL ,
    FILE_IDENTIFIER CHARACTER VARYING (50) NOT NULL ,
    MIME_TYPE       CHARACTER VARYING (256) NOT NULL ,
    CHECKSUM        CHARACTER VARYING (64) NOT NULL ,
	ORIGINAL_FILE_SIZE  BIGINT NOT NULL ,
    ENCRYPTED_FILE_SIZE BIGINT NOT NULL ,
    TOTAL_PART          INTEGER NOT NULL ,
    SORT_ORDER      SMALLINT NOT NULL ,
    IS_FULLTEXT_PARSED BOOL NULL,
    IS_PREVIEW_GENERATED BOOL NULL;
    ITEM_ID         BIGINT NOT NULL
  ) ;
CREATE INDEX FILE_REF_ITEM_ID_IDX ON FILE_REFERENCE
  ( ITEM_ID
  ) ;
ALTER TABLE FILE_REFERENCE ADD CONSTRAINT FILE_REFERENCE_PK PRIMARY KEY ( ID ) ;
ALTER TABLE FILE_REFERENCE ADD CONSTRAINT FILE_REFERENCE_UK UNIQUE ( FILE_IDENTIFIER ) ;

CREATE TABLE PREVIEW
  (
    ID                BIGINT NOT NULL ,
    FILE_REFERENCE_ID BIGINT NOT NULL ,
    FILE_IDENTIFIER   CHARACTER VARYING (50) NOT NULL,
    SORT_ORDER        SMALLINT NOT NULL
  );
ALTER TABLE PREVIEW ADD CONSTRAINT PREVIEW_PK PRIMARY KEY ( ID ) ;
ALTER TABLE PREVIEW ADD CONSTRAINT PREV_F_REF_UK UNIQUE ( FILE_IDENTIFIER ) ;
ALTER TABLE PREVIEW ADD CONSTRAINT PREV_F_REF_AND_SORT_UK UNIQUE ( FILE_IDENTIFIER,  SORT_ORDER ) ;
ALTER TABLE PREVIEW ADD CONSTRAINT PREV_F_IDENT_AND_F_REF_UK UNIQUE ( FILE_IDENTIFIER,  FILE_REFERENCE_ID ) ;
ALTER TABLE PREVIEW ADD CONSTRAINT PREV_TO_FILE_REF_FK FOREIGN KEY (FILE_REFERENCE_ID) REFERENCES FILE_REFERENCE (ID) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ;

CREATE INDEX PREVIEW_FILE_REF_ID_IDX ON PREVIEW
  (
    FILE_REFERENCE_ID
  ) ;


CREATE TABLE ITEM
  (
    ID BIGINT NOT NULL ,
    NAME CHARACTER VARYING(255) ,
    TYPE          CHAR (1) NOT NULL ,
    CREATED       TIMESTAMP (0) WITHOUT TIME ZONE NOT NULL ,
    LAST_MODIFIED TIMESTAMP (0) WITHOUT TIME ZONE NOT NULL
  ) ;
ALTER TABLE ITEM ADD CONSTRAINT ITM_TYPE_CHECK CHECK (TYPE = 'D' OR TYPE = 'F') ;

CREATE INDEX ITEM_CREATED_IDX ON ITEM
  ( CREATED
  ) ;
CREATE INDEX ITEM_LAST_MODIFIED_IDX ON ITEM
  ( LAST_MODIFIED
  ) ;
--  This is Accent-Insensitive index, speed up NAME like '%ABC%' queries
CREATE INDEX ITEM_NAME_GIN_IDX ON ITEM USING gin
  (
    public.unaccent_lower(NAME) public.gin_trgm_ops
  ) ;
-- GIN index do not support comparison, so adding a regular B-tree index too to speed-up ORDER BY: also done with "C" ("POSIX") collation
CREATE INDEX ITEM_NAME_BTREE_IDX ON ITEM
  (
    public.unaccent_lower(NAME) COLLATE "C"
  ) ;
CREATE INDEX ITEM_TYPE_IDX ON ITEM
  (
    TYPE
  ) ;
ALTER TABLE ITEM ADD CONSTRAINT ITEM_PK PRIMARY KEY ( ID ) ;

CREATE TABLE DOCUMENT
(
  ID SERIAL NOT NULL ,
  FILE_IDENTIFIER CHARACTER VARYING (50) NOT NULL,
  DOC_TEXT text NOT NULL,
  TSV tsvector NOT NULL,
  LANGUAGE text NOT NULL
);
ALTER TABLE DOCUMENT ADD CONSTRAINT DOC_TO_FILE_REF_FK FOREIGN KEY (FILE_IDENTIFIER)
        REFERENCES FILE_REFERENCE (FILE_IDENTIFIER) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ;
ALTER TABLE DOCUMENT ADD CONSTRAINT DOCUMENT_FILE_IDENT_UK  UNIQUE (FILE_IDENTIFIER);
ALTER TABLE DOCUMENT ADD CONSTRAINT DOCUMENT_PK PRIMARY KEY ( ID );

CREATE INDEX DOCUMENT_ID_IDX ON DOCUMENT (ID);
CREATE INDEX DOCUMENT_FILE_IDENT_IDX ON DOCUMENT (FILE_IDENTIFIER);
CREATE INDEX DOCUMENT_FTSV_IDX ON DOCUMENT USING gin (TSV);
CREATE INDEX DOCUMENT_LANGUAGE_IDX ON DOCUMENT (LANGUAGE);




CREATE TABLE TAG_DEFINITION
  (
    ID BIGINT NOT NULL ,
    CODE              CHARACTER VARYING (25) NOT NULL ,
    TYPE              CHARACTER VARYING (25) NOT NULL ,
    STRING_TAG_LENGTH SMALLINT ,
    DEFAULT_VALUE     CHARACTER VARYING(255)
  ) ;
ALTER TABLE TAG_DEFINITION ADD CONSTRAINT TAG_PK PRIMARY KEY ( ID ) ;
ALTER TABLE TAG_DEFINITION ADD CONSTRAINT TAG_CODE_UK UNIQUE ( CODE ) DEFERRABLE INITIALLY DEFERRED;


CREATE TABLE TAG_VALUE
  (
    ID     SERIAL NOT NULL,
    TAG_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    VALUE_BOOLEAN BIT,
    VALUE_STRING CHARACTER VARYING(2000) ,
    VALUE_INTEGER  NUMERIC (20, 0) ,
    VALUE_DOUBLE   NUMERIC (20, 5),
    VALUE_DATE     DATE ,
    VALUE_DATETIME TIMESTAMP (0) WITHOUT TIME ZONE
  ) ;

CREATE INDEX TAG_VALUE_BOOLEAN_IDX ON TAG_VALUE  ( VALUE_BOOLEAN );
CREATE INDEX TAG_VALUE_INTEGER_IDX ON TAG_VALUE (  VALUE_INTEGER  ) ;
CREATE INDEX TAG_VALUE_DOUBLE_IDX ON TAG_VALUE  (  VALUE_DOUBLE  ) ;
CREATE INDEX TAG_VALUE_DATE_IDX ON TAG_VALUE  (  VALUE_DATE  ) ;
CREATE INDEX TAG_VALUE_DATETIME_IDX ON TAG_VALUE  ( VALUE_DATETIME  ) ;
CREATE INDEX TAG_VALUE_STR_LIKE_GIN_IDX ON TAG_VALUE USING gin
  (
    unaccent_lower(VALUE_STRING) gin_trgm_ops
  ) ;

CREATE INDEX TAG_VALUE_STR_SORT_BTREE_IDX ON TAG_VALUE
  (
    unaccent_lower(VALUE_STRING) COLLATE "C"
  ) ;

ALTER TABLE TAG_VALUE ADD CONSTRAINT TAG_VALUE_PK PRIMARY KEY ( ID ) ;


ALTER TABLE FILE_REFERENCE ADD CONSTRAINT FILE_REFERENCE_ITEM_FK FOREIGN KEY ( ITEM_ID ) REFERENCES ITEM ( ID ) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;


