CREATE ROLE {{doka_user}} WITH
	SUPERUSER
	CREATEDB
	NOCREATEROLE
	INHERIT
	LOGIN
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1;
ALTER USER doka PASSWORD '{{doka_password}}';

GRANT CONNECT ON DATABASE postgres TO {{doka_user}};
GRANT CREATE, USAGE ON SCHEMA public TO {{doka_user}};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO {{doka_user}};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO {{doka_user}};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO {{doka_user}};