[package]
name = "dkcrypto"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_derive = { workspace = true }
log = { workspace = true }
log4rs = { workspace = true }
schemars = { workspace = true }
rand = { workspace = true }
base64 = { workspace = true }
rayon = "1.6"

anyhow = { workspace = true }
bcrypt = { workspace = true }
sha2 = "^0.10"
ring = "^0.16"
orion = "0.17.4"

commons-error = {path="../commons-error"}

#test only
[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false



